import { readFileSync, writeFileSync } from "node:fs";

const dashboard = readFileSync(new URL("./dashboard.html", import.meta.url), "utf8");
const portal = readFileSync(new URL("./portal.html", import.meta.url), "utf8");

const out = `// Generated by build-pages.js from dashboard.html and portal.html. Do not edit directly.
export const DASHBOARD_HTML = ${JSON.stringify(dashboard)};
export const PORTAL_HTML = ${JSON.stringify(portal)};
`;

writeFileSync(new URL("./pages.generated.js", import.meta.url), out);
console.log("wrote pages.generated.js");
